# Generated by Django 5.2.9 on 2026-01-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., OpenAI, Midjourney', max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='API Base URL (e.g., https://api.openai.com/v1)')),
                ('api_key', models.CharField(help_text='Securely stored API Key', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display Name (e.g., DALL-E 3)', max_length=100)),
                ('api_id', models.CharField(help_text='Model ID expected by the API (e.g., dall-e-3)', max_length=100)),
                ('version', models.CharField(blank=True, help_text='Optional version string', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_params', models.JSONField(blank=True, default=dict, help_text='Default generation parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_engine.aiprovider')),
            ],
            options={
                'unique_together': {('provider', 'api_id')},
            },
        ),
    ]
