# Generated by Django 5.2.9 on 2025-12-10 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('ai_model', models.CharField(blank=True, help_text='AI model/tool used (e.g., ChatGPT-4, Claude, Gemini)', max_length=100)),
                ('example_output', models.TextField(blank=True, help_text='Example output from this prompt')),
                ('output_image', models.ImageField(blank=True, help_text='Example image output', null=True, upload_to='prompt_outputs/images/')),
                ('output_video', models.FileField(blank=True, help_text='Example video output', null=True, upload_to='prompt_outputs/videos/')),
                ('output_audio', models.FileField(blank=True, help_text='Example audio output', null=True, upload_to='prompt_outputs/audio/')),
                ('output_type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('code', 'Code')], help_text='Type of output example', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('use_case', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('trend_score', models.FloatField(default=0.0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow')], max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vault.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vault.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField()),
                ('old_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vault.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='PromptView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='vault.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vault.prompt')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='vault.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower', 'following'], name='vault_follo_followe_5680e9_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['owner', 'is_public'], name='vault_promp_owner_i_3dad38_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_public', '-trend_score'], name='vault_promp_is_publ_e74127_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-created_at'], name='vault_promp_created_32bacd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='vault_notif_user_id_dddab9_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'prompt'], name='vault_like_user_id_2d495c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'prompt')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['prompt', '-created_at'], name='vault_comme_prompt__d3cddb_idx'),
        ),
        migrations.AddIndex(
            model_name='promptview',
            index=models.Index(fields=['user', 'prompt'], name='vault_promp_user_id_ff6a18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promptview',
            unique_together={('user', 'prompt')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='vault_repor_status_e099bf_idx'),
        ),
        migrations.AddIndex(
            model_name='savedprompt',
            index=models.Index(fields=['user', '-created_at'], name='vault_saved_user_id_db96fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedprompt',
            unique_together={('user', 'prompt')},
        ),
    ]
