# Generated by Django 5.2.9 on 2025-12-29 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_convert_ai_model_to_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='fork_depth',
            field=models.PositiveIntegerField(default=0, help_text='Distance from original (0 = original)'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='original_creator',
            field=models.ForeignKey(blank=True, help_text='The user who created the root ancestor of this prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_created_prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='parent_prompt',
            field=models.ForeignKey(blank=True, help_text='The prompt this was forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='vault.prompt'),
        ),
        migrations.AddField(
            model_name='promptview',
            name='source',
            field=models.CharField(default='direct', help_text="e.g., 'qr', 'web_share', 'search'", max_length=50),
        ),
        migrations.CreateModel(
            name='PromptUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_method', models.CharField(choices=[('scroll', 'Scroll to Bottom'), ('run', 'Run Prompt'), ('creator', 'Creator')], max_length=20)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='vault.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'prompt'], name='vault_promp_user_id_e697be_idx')],
                'unique_together': {('user', 'prompt')},
            },
        ),
    ]
