# Generated by Django 5.2.9 on 2025-12-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAUth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_public',
            field=models.BooleanField(default=False),
        ),
    ]
